### ISSUE TITLE
Documentation should not be in Wiki

### ISSUE THREAD

**Issue by iamstarkov** [4urbanoff/nali#1]
Documentation should be in markdown files, because they are stored in git, can be transformed into other formats and other benefits over github wiki

**Comment by iminside** [comment]
Если я правильно понял смысл автоперевода:

"Документация должна быть в уценки файлов, так как они хранятся в Git, могут быть преобразованы в другие форматы и других преимуществ по сравнению с GitHub вики"

отвечу, что документация и так написана в markdowm файлах. Поправьте меня, если я что-то недопонял.

**Comment by iamstarkov** [comment]
Сейчас [документация](https://github.com/4urbanoff/nali/wiki) храниться в вики гитхаба вне репозитория, а не в md-файлах. Примером для подражания может служить [README](https://github.com/4urbanoff/nali/blob/master/README.md)

**Comment by iminside** [comment]
Да в вики в md-файлах. Вы имеете ввиду, что её надо перенести в сам репозиторий?

**Comment by iamstarkov** [comment]
верно

**Comment by iamstarkov** [comment]
неважно
