### ISSUE TITLE
Документация на английском

### ISSUE THREAD

**Issue by iamstarkov** [4urbanoff/nali#2]
Кажется, что это стандарт

**Comment by iminside** [comment]
Честно говоря у меня с английским туго, а переводчиком пользоваться, я думаю, бессмысленно ибо автоперевод будет с большими неточностями. Тут нужна помощь грамотного в этом человека.

**Comment by iamstarkov** [comment]
понятно, ну тогда можно будет ждать волонтёра, а пока ишью можно закрыть
