### ISSUE TITLE
FileUtils error

### ISSUE THREAD

**Issue by Shggz** [4urbanoff/nali#3]
shgz@S500:~/RubymineProjects$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
shgz@S500:~/RubymineProjects$ nali new sample
/home/shgz/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/nali-0.4.0/lib/nali/generator.rb:21:in `create_application': uninitialized constant Nali::Generator::FileUtils (NameError)
    from /home/shgz/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/nali-0.4.0/lib/nali/generator.rb:7:in`initialize'
    from /home/shgz/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/nali-0.4.0/bin/nali:13:in `new'
    from /home/shgz/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/nali-0.4.0/bin/nali:13:in`<top (required)>'
    from /home/shgz/.rbenv/versions/2.2.0/bin/nali:23:in `load'
    from /home/shgz/.rbenv/versions/2.2.0/bin/nali:23:in`<main>'

**Comment by iminside** [comment]
Исправлено с версии 0.4.1, спасибо за pull request!
